# Generated by Django 4.2.4 on 2023-08-21 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fsgui", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="networks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="User",),
    ]
