# Generated by Django 4.2.4 on 2023-08-23 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fsgui", "0007_remove_flowspec_icmpcode_remove_flowspec_icmptype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowspec", name="dstip", field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="flowspec",
            name="srcip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="network", name="net", field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name="network", unique_together={("net", "user", "cidr")},
        ),
    ]
