# Generated by Django 4.2.4 on 2023-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsgui", "0009_alter_flowspec_dstip_alter_flowspec_srcip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowspec", name="dstcidr", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="flowspec", name="dstprt", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="flowspec",
            name="srccidr",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="flowspec", name="srcprt", field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="network", name="cidr", field=models.IntegerField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name="flowspec",
            unique_together={
                (
                    "net",
                    "srcip",
                    "srccidr",
                    "srcprt",
                    "dstip",
                    "dstcidr",
                    "dstprt",
                    "protocol",
                )
            },
        ),
    ]
