# Generated by Django 4.2.4 on 2023-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsgui", "0010_alter_flowspec_dstcidr_alter_flowspec_dstprt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network", name="cidr", field=models.IntegerField(),
        ),
    ]
