# Generated by Django 4.2.4 on 2023-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsgui", "0011_alter_network_cidr"),
    ]

    operations = [
        migrations.RemoveField(model_name="network", name="ipversion",),
        migrations.AlterField(
            model_name="flowspec",
            name="dstcidr",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="flowspec", name="dstprt", field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="flowspec",
            name="srcprt",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
