# Generated by Django 4.2.4 on 2023-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsgui", "0012_remove_network_ipversion_alter_flowspec_dstcidr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowspec",
            name="dstcidr",
            field=models.CharField(max_length=10),
        ),
    ]
