# Generated by Django 4.2.4 on 2023-08-25 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fsgui", "0014_alter_flowspec_srccidr"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="network", unique_together=set(),),
        migrations.AlterField(
            model_name="network", name="net", field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="network", unique_together={("net", "user")},
        ),
        migrations.RemoveField(model_name="network", name="cidr",),
    ]
