# Generated by Django 4.2.4 on 2023-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsgui", "0016_alter_flowspec_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowspec",
            name="dstprt",
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name="flowspec",
            name="srcprt",
            field=models.IntegerField(blank=True, max_length=6),
        ),
    ]
