# Generated by Django 4.2.4 on 2023-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsgui", "0017_alter_flowspec_dstprt_alter_flowspec_srcprt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowspec", name="dstprt", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="flowspec",
            name="protocol",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="flowspec", name="srcprt", field=models.IntegerField(),
        ),
    ]
