# Generated by Django 4.2.4 on 2023-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsgui", "0019_alter_flowspec_dstprt_alter_flowspec_srcprt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowspec",
            name="dstprt",
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name="flowspec",
            name="srcip",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flowspec",
            name="srcprt",
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
